services:

    phpbbservices.selectivemassemails.listener:
        class: phpbbservices\selectivemassemails\event\main_listener
        arguments:
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%core.php_ext%'
            - '@request'
        tags:
            - { name: event.listener }
